# Generated by Django 5.0.6 on 2024-06-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.IntegerField()),
                ('pro_name', models.CharField(max_length=100)),
                ('pro_details', models.TextField()),
                ('pro_image', models.ImageField(upload_to='Product')),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
